name: CI for Function Executor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd cc_project/server
          npm install

      - name: Build Python Docker image
        run: docker build -f cc_project/server/docker/Dockerfile.python -t python-func .

      - name: Build JS Docker image
        run: docker build -f cc_project/server/docker/Dockerfile.js -t js-func .

      - name: Run tests
        run: npm test
